[UI_SETTINGS]
window_width  = 1300
window_height = 820
window_x      = 80
window_y      = 80

[LASER_RANGING]
; serial | tcp/ip
connection_type = serial
tcp_ip_address  = 192.168.1.7
tcp_port        = 20108

[CAMERA]
rtsp_url = rtsp://admin:12qwaszx@192.168.1.68:554/stream1
camera_control_method = pelco_d  ; onvif или pelco_d
onvif_ip = 192.168.1.68
onvif_username = admin
onvif_password = 12qwaszx
onvif_port = 80
pelco_d_ip = 192.168.1.120:80  ; IP-адрес камеры с Pelco-D по TCP
; Параметры для уменьшения задержки видео
buffer_size = 1
frame_width = 640
frame_height = 480
fps = 30

[PAN_TILT]
; Теперь поворотка управляется тем же протоколом, что и для камеры
; host и port больше не нужны, так как используется тот же канал, что и для камеры