[UI_SETTINGS]
window_width  = 1300
window_height = 820
window_x      = 80
window_y      = 80

[LASER_RANGING]
; serial | tcp/ip
connection_type = serial
tcp_ip_address  = 192.168.1.7
tcp_port        = 20108

[CAMERA]
rtsp_url = rtsp://admin:12qwaszx@192.168.1.68:554/stream1
enable_onvif = true
onvif_ip = 192.168.1.68
onvif_username = admin
onvif_password = 12qwaszx
onvif_port = 80
use_pelco_d = false
pelco_d_port = COM1